{
    'name':'Asset Manager',
    'version':'0.7',
    'category':'Administration',
    'description':' App used for mananging computers, printers, phones and other assets',
    'depends': ['base','hr','mail'],
    'data':[
        'security/ir.model.access.csv',
        'views/menu_view.xml',
        'views/computer_views.xml',
        'views/project_views.xml',
        'views/monitor_views.xml',
        'views/software_views.xml',
        'views/license_views.xml',
        'views/history_views.xml',
        'views/printer_views.xml',
        'views/other_views.xml',
        'views/inventory_views.xml',
        'views/phone_tablet_views.xml',
        'views/tag_views.xml',
        'views/score_views.xml',
        'views/computer_category_views.xml',
        'views/car_views.xml',
        'data/mail_template.xml',
        'data/ir_cron_data.xml',
        'views/tempFolder/server_view.xml',
        'views/tempFolder/furniture_views.xml'

    ],
    'post_load': 'post_load', 
    'installable':True,
    'application':True,
    'auto_install':False,
}
